---
title: "The summary of missing data"
author: "ChenYW"
date: "`r Sys.Date()`"
output:
  html_document: 
    css: style.css
    df_print: kable
    fig_caption: yes
    highlight: textmate
    keep_md: yes
    number_sections: yes
    theme: readable
    toc: yes
  pdf_document: 
    extra_dependencies: xcolor
    fig_caption: yes
    highlight: tango
    includes: null
    keep_tex: yes
    number_sections: yes
    toc: yes
    toc_depth: 4
  word_document:
    toc: yes
geometry: margin = 0.8in
header-includes:
- \usepackage{color,xcolor,chngcntr,setspace,placeins,fancyhdr, url}
- \usepackage[ruled,vlined,linesnumbered]{algorithm2e}
- \onehalfspacing
- \counterwithin{equation}{section}
- \counterwithin{table}{section}
- \pagestyle{fancy}
linkcolor: black
editor_options: null
chunk_output_type: inline
urlcolor: black
---

```{r , include= T, echo = F}
knitr::opts_chunk$set(echo = TRUE, message = FALSE, warning = FALSE)
# , class.source = "BK"
rm(list=ls())
# suppressMessages(Sys.setlocale("LC_TIME", "English"))
```


```{r R, include=T, echo = F}
########################################################
# .rmdenvir = environment()
# .refctr <- c(`_` = 0)
########################################################
library(data.table);
library(dplyr)
library(latex2exp);
library(knitr)
library(kableExtra)
```

<!-- # Validation based on the noise from t distribution -->
<!-- ###################################################################### -->

# Summary of missing PM2.5 data from 2015th to 2017th
```{r echo=FALSE}
library(data.table)
load("H:/Github/MissingData/Miss_data_2015_2017.RData")
# setorderv(Miss_data)
# kable(Miss_data, booktabs = TRUE
#                , longtable = TRUE 
#       , format = "html"
#                , caption = "Summary of missing data"
#                , align = c("l", "c", "l", "c", "c", "c")) %>%
#   row_spec(0, bold = TRUE ) %>%
#   kable_styling(latex_options = "striped" 
#                 , stripe_color = "ltgray"
#                   , position = "center",
#                 font_size = 12)%>%  
#   #  kable_styling(full_width = F) %>%
#   scroll_box(width = "1000px", height = "1000px")
library(DT)
DT::datatable(Miss_data_2015_2017, options = list(columnDefs = list(list(
  targets = 5,
  render = JS(
    "function(data, type, row, meta) {",
    "return type === 'display' && data.length > 6 ?",
    "'<span title=\"' + data + '\">' + data.substr(0, 6) + '...</span>' : data;",
    "}")
))), callback = JS('table.page(3).draw(false);'))
```

# Summary of missing PM2.5 data from 2010th to 2020th
```{r echo=FALSE}
setwd("H:/Github/MissingData")
library(data.table)
load("H:/Github/MissingData/Miss_data_2010_2020.RData")
# setorderv(Miss_data)
# kable(Miss_data, booktabs = TRUE
#                , longtable = TRUE 
#       , format = "html"
#                , caption = "Summary of missing data"
#                , align = c("l", "c", "l", "c", "c", "c")) %>%
#   row_spec(0, bold = TRUE ) %>%
#   kable_styling(latex_options = "striped" 
#                 , stripe_color = "ltgray"
#                   , position = "center",
#                 font_size = 12)%>%  
#   #  kable_styling(full_width = F) %>%
#   scroll_box(width = "1000px", height = "1000px")
library(DT)
DT::datatable(Miss_data_2010_2020, options = list(columnDefs = list(list(
  targets = 5,
  render = JS(
    "function(data, type, row, meta) {",
    "return type === 'display' && data.length > 6 ?",
    "'<span title=\"' + data + '\">' + data.substr(0, 6) + '...</span>' : data;",
    "}")
))), callback = JS('table.page(3).draw(false);'))
```
